# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 84ce099e60628344c1cd07f5e45e94d5e8556788079fae6da8f64ca78ecfeb33f2212a0fbf036cca18d71a72eb06a16bd31ce8e033695d03bd4947d8a0566bf7

test:
  secret_key_base: 8090afc2a45c8e478f355188dc9c94c60241da0ef38426ad5e0afc94e4f7716ff53fbf00679f01dc61c3e4e424dbd3306ecbd067aa767a452f2f2f59a221360c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
